default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      #- id: no-commit-to-branch
      #  args: ["--branch", "main"]
      - id: check-added-large-files
        args: ["--maxkb=50"]
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: hatch run lint:lint
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
      - id: format
        name: format
        entry: hatch run lint:format
        language: system
        types: [python]
        pass_filenames: false
        verbose: true
exclude: |
  (?x)(
    ^lib/|
    ^dataset/
  )
